/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pj4uBIO5maH
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function imageBox() {
  return (
    <div className="flex flex-col items-center space-y-4">
      <form className="w-full max-w-sm space-y-4">
        <div className="flex flex-col space-y-1.5">
          <Label htmlFor="image">Upload Image</Label>
          <Input accept="image/*" id="image" type="file" />
        </div>
        <Button type="submit">Submit</Button>
      </form>
      <div className="w-full max-w-sm">
        <img
          alt="Uploaded Image"
          className="aspect-square object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800 dark:border-gray-800"
          height={500}
          src="/placeholder.svg"
          width={500}
        />
      </div>
    </div>
  )
}
